FROM python:3.9

RUN pip install pgadmin4 gunicorn

ENTRYPOINT ["gunicorn", \
    "--bind", "0.0.0.0:5050", \
    "--workers", "1", \
    "--threads","4", \
    "--chdir","/usr/local/lib/python3.9/site-packages/pgadmin4", \
    "pgAdmin4:app" ]